# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options
image:
  name: mjyocca/tfci:latest

.tfc:upload_configuration:
  script:
    - tfci -hostname=$TF_HOSTNAME -token=$TF_API_TOKEN -organization=$TF_CLOUD_ORGANIZATION upload -workspace=$WORKSPACE -speculative=$SPECULATIVE -directory=$DIRECTORY
  artifacts:
    paths:
      - "${CI_JOB_NAME}_payload.json"
    reports:
      dotenv: .env

.tfc:create_run:
  variables:
    CONFIGURATION_VERSION_ID: $configuration_version_id
    MESSAGE: ""
    VAR_FILE: ""
  script:
    - tfci -hostname=$TF_HOSTNAME -token=$TF_API_TOKEN -organization=$TF_CLOUD_ORGANIZATION run create -workspace=$WORKSPACE -configuration_version=$CONFIGURATION_VERSION_ID -message=$MESSAGE -var-file=$VAR_FILE -plan-only=$PLAN_ONLY
  artifacts:
    reports:
      dotenv: .env

.tfc:apply_run:
  variables:
    RUN_ID: $run_id
    COMMENT: "LGTM"
  script:
    - tfci -hostname=$TF_HOSTNAME -token=$TF_API_TOKEN -organization=$TF_CLOUD_ORGANIZATION run apply -run=$RUN_ID -comment=$COMMENT
  artifacts:
    reports:
      dotenv: .env

.tfc:plan_output:
  variables:
    PLAN_ID: $plan_id
  script:
    - tfci -hostname=$TF_HOSTNAME -token=$TF_API_TOKEN -organization=$TF_CLOUD_ORGANIZATION plan output -plan=$PLAN_ID
  artifacts:
    paths:
      - "${CI_JOB_NAME}_payload.json"
    reports:
      dotenv: .env

.tfc:comment_on_merge_request:
  image: alpine/curl
  variables:
    MR_COMMENT: |
      Plan: ${add} to add, ${change} to change, ${destroy} to destroy.
      [Terraform Cloud Plan](${run_link})
  script:
    - 'curl --request POST --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes" --data-urlencode "body=$MR_COMMENT"'
